with-expecter: True
packages:
  github.com/jmarren/deepfried/util:
    interfaces:
      IURL:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockURL
          inpackage: True
      IValues:
          config:
          dir: "{{.InterfaceDir}}"
          mockName: MockValues
          inpackage: True



  # github.com/jmarren/deepfried/handlers:
  #   interfaces:
  #     TagService:
  #       config:
  #         dir: "{{.InterfaceDir}}"
  #         mockName: MockTagService
  #         inpackage: True
  #     UserService:
  #       config:
  #         dir: "{{.InterfaceDir}}"
  #         mockName: MockUserService
  #         inpackage: True
