// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HtmlStyle() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`height:100vh;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-y:scroll;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column;`)
	templ_7745c5c3_CSSID := templ.CSSID(`HtmlStyle`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func Button() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSID := templ.CSSID(`Button`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func Slabo27Reg() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:"Slabo 27px", serif;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:400;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-style:normal;`)
	templ_7745c5c3_CSSID := templ.CSSID(`Slabo27Reg`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func Root() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`--dark-gray:#171717;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--tertiary-color:#7f9299;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--tertiary-dark:#0d182b;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--secondary-background-color:white;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--cta-color:#098afd;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--border-color-one:#e1e3e3;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--hover-color-one:#d9d1cc;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--text-color-one:black;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--light-gray-one:#969284;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--light-gray-two:#d1d1d1;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--input-color-one:#454545;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--player-height:100px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--medium-image-size:100px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--box-shadow-one:2px 10px 25px #e6e7e8;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--bpm-slider-min:0%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--bpm-slider-max:0%;`)
	templ_7745c5c3_CSSID := templ.CSSID(`Root`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func BodyStyle() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:linear-gradient(0deg, #1e1e1e , #292828);  
    position: relative;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow:auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:Inter;`)
	templ_7745c5c3_CSSID := templ.CSSID(`BodyStyle`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func ProfilePhoto() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`object-fit:cover;`)
	templ_7745c5c3_CSSBuilder.WriteString(`clip-path:circle(50% at 50% 50%);`)
	templ_7745c5c3_CSSID := templ.CSSID(`ProfilePhoto`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

/*
  .profile-photo>img{
    width: 100%;
    height: 100%;
  }

*/

func PageContent() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-x:hidden;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-top:60px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-left:75px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding-bottom:10px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`left:240px;`)
	templ_7745c5c3_CSSID := templ.CSSID(`PageContent`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func IconMed() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:15px;`)
	templ_7745c5c3_CSSID := templ.CSSID(`IconMed`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func IconContainer() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:10px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSID := templ.CSSID(`IconContainer`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func Top() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`z-index:4;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:rgba(0.0, 0.0, 0.0, 50%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`transition:background-color 0.3s cubic-bezier(0.15, 0.83, 0.66, 1);`)
	templ_7745c5c3_CSSID := templ.CSSID(`Top`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func KatanaCard() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid #32363d;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:#131717; 
    border-radius: 10px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:white;`)
	templ_7745c5c3_CSSID := templ.CSSID(`KatanaCard`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

var BaseStyles = []templ.CSSClass{
	HtmlStyle(),
	Button(),
	KatanaCard(),
	Top(),
	IconMed(),
	PageContent(),
	ProfilePhoto(),
	BodyStyle(),
	Root(),
	Slabo27Reg(),
}

var _ = templruntime.GeneratedTemplate
