// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/jmarren/deepfried/services"

func JustAddedSection(j []*services.PlayableElt) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"just-added-card\" class=\"\"><div id=\"just-added-header\">Just Added</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, item := range j {
			templ_7745c5c3_Err = CarouselCardBody(item).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

/*
			<div class=" katana-card track-card-container just-added-card fade-in-slowly">
				<div class="card-initial">
					<button
						class="playable"
						hx-get="/player"
						hx-target="#player"
						hx-audio={ item.ID.String() }
						hx-audio-toggle-fx="class white-track-card"
						hx-audio-toggle-target="closest .track-card-container"
						hx-swap="outerHTML"
					>
						<img class="artwork" src={ item.ArtworkSrc }/>
					</button>
					<div class="track-info">
						<span class="item.profile-image-container">
							<img class="profile-photo-small profile-photo" src={ item.ProfilePhotoSrc }/>
						</span>
						<span class="track-info-right">
							<span
								class="card-title clickable-text"
								hx-trigger="click"
								hx-get={ fmt.Sprintf("%s/%s", item.Username, item.Title) }
								hx-target="#page-content"
								hx-push-url="true"
							>{ item.Title }</span>
							<span
								class="item.username clickable-text"
								hx-get={ fmt.Sprintf("/%s", item.Username) }
								hx-target="#page-content"
								hx-push-url="true"
							>
								{ item.Username }
							</span>
							<span class="item.bpm">
								{ fmt.Sprintf("%d", item.Bpm) } bpm
							</span>
							<span class="spacer"></span>
						</span>
					</div>
					if item.IsPlaying {
						<div id="playing-indicator">
							<div id="playing-indicator-content">
								<div class="triangle-forward-container">
									<div class="triangle control triangle-forward"></div>
								</div>
							</div>
						</div>
					}
				</div>
				<div id="extra-info"></div>
			</div>
		}
	</div>
}
*/

func JustAddedSectionHead() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style id=\"featured-section-tags\">\n\t#just-added-card {\n\t    border: 1px solid #32363d;\n\t    border-radius: 10px;\n\t    color: white;\n\t    font-family: Inter;\n\t    position: relative;\n\t    width: 200px;\n\t    margin-left: 10px;\n\t}\n\n\t#just-added-header {\n\t\tposition: absolute;\n\t\ttop: -0.5em;\n\t\tleft: -0.5em;\n\t\tfont-weight: 600;\n\t\tfont-size: 12px;\n\t\tpadding: 2px 8px;\n\t\tcolor: var(--dark-gray);\n\t\tbackground-color: white;\n\t\tborder-radius: 4px;\n\t}\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
